	db "MASTER BALL@"
	db "HYPER BALL@"
	db "POUDRECLAIRE@"
	db "SUPER BALL@"
	db "# BALL@"
	db "HONOR BALL@"
	db "BICYCLETTE@"
	db "PIERRE LUNE@"
	db "ANTIDOTE@"
	db "ANTI-BRULE@"
	db "ANTI-GEL@"
	db "REVEIL@"
	db "ANTI-PARA@"
	db "GUERISON@"
	db "POTION MAX@"
	db "HYPER POTION@"
	db "SUPER POTION@"
	db "POTION@"
	db "CORDE SORTIE@"
	db "REPOUSSE@"
	db "ELIXIR MAX@"
	db "PIERRE FEU@"
	db "PIERREFOUDRE@"
	db "PIERRE EAU@"
	db "GARDE PSN.@"
	db "PV PLUS@"
	db "PROTEINE@"
	db "FER@"
	db "CARBONE@"
	db "POING CHANCE@"
	db "CALCIUM@"
	db "SUPER BONBON@"
	db "PRECISION +@"
	db "PIERREPLANTE@"
	db "POUDRE METAL@"
	db "PEPITE@"
	db "#POUPEE@"
	db "TOTAL SOIN@"
	db "RAPPEL@"
	db "RAPPEL MAX@"
	db "GARDE-STATS@"
	db "SUPEREPOUSSE@"
	db "MAX REPOUSSE@"
	db "MUSCLE +@"
	db "GARDE BRU.@"
	db "EAU FRAICHE@"
	db "SODA POP@"
	db "LIMONADE@"
	db "ATTAQUE +@"
	db "GARDE GEL@"
	db "DEFENSE +@"
	db "VITESSE +@"
	db "ATK.SPE. +@"
	db "BOITE JETONS@"
	db "CHERCH'OBJET@"
	db "# FLUTE@"
	db "MULTI EXP.@"
	db "CANNE@"
	db "SUPER CANNE@"
	db "FEUILLE ARG.@"
	db "MEGA CANNE@"
	db "PP PLUS@"
	db "HUILE@"
	db "HUILE MAX@"
	db "ELIXIR@"
	db "ECAILLEROUGE@"
	db "POTIONSECRET@"
	db "PASSE BATEAU@"
	db "OEUF MYSTERE@"
	db "GLAS TRANSP.@"
	db "ARGENT'AILE@"
	db "LAIT MEUMEU@"
	db "VIVE GRIFFE@"
	db "BAIE PECHA@"
	db "FEUILLE OR@"
	db "SABLE DOUX@"
	db "BEC POINTU@"
	db "BAIE CERIZ@"
	db "BAIE WILLIA@"
	db "BAIE FRAIVE@"
	db "PIC VENIN@"
	db "ROCHE ROYALE@"
	db "BAIE KIKA@"
	db "BAIE MARON@"
	db "NOIGRUME RGE@"
	db "MINICHAMPI@"
	db "GROCHAMPI@"
	db "POUDRE ARG.@"
	db "NOIGRUME BLU@"
	db "GARDE SOM.@"
	db "PIECE RUNE@"
	db "NOIGRUME JNE@"
	db "NOIGRUME VRT@"
	db "RUNE PURIF.@"
	db "EAU MYSTIQUE@"
	db "CUILLERTORDU@"
	db "NOIGRUME BLC@"
	db "CENT.NOIRE@"
	db "NOIGRUME NOI@"
	db "GARDE PARA@"
	db "NOIGRUME ROS@"
	db "LUNET.NOIRES@"
	db "QUEUERAMOLOS@"
	db "RUBAN ROSE@"
	db "BATON@"
	db "BOULE FUMEE@"
	db "GLACETERNEL@"
	db "AIMANT@"
	db "BAIE PRINE@"
	db "PERLE@"
	db "GROSSE PERLE@"
	db "PIERRE STASE@"
	db "RUNE SORT@"
	db "BONBON RAGE@"
	db "GS BALL@"
	db "CARTE BLEUE@"
	db "GRAIN.MIRACL@"
	db "MASSE OS@"
	db "BANDEAU@"
	db "GARDE CONF.@"
	db "POUDRENERGIE@"
	db "RACINENERGIE@"
	db "POUDRE SOIN@"
	db "HERBE RAPPEL@"
	db "PIERRE DURE@"
	db "OEUF CHANCE@"
	db "PASSE.MAGN.@"
	db "PARTIE MACH.@"
	db "TICKET OEUF@"
	db "OBJET PERDU@"
	db "POUSS.ETOILE@"
	db "MORC. ETOILE@"
	db "CLE SOUS-SOL@"
	db "PASSE TRAIN@"
	db "NAUTILE@"
	db "FOSSILE DOME@"
	db "VIEIL AMBRE@"
	db "CHARBON@"
	db "JUS DE BAIE@"
	db "LENTILSCOPE@"
	db "COLIS CHEN@"
	db "HERBE POUV.@"
	db "PEAU METAL@"
	db "CROC DRAGON@"
	db "CHARME AMI@"
	db "RESTES@"
	db "RECHERCHES@"
	db "TERU-SAMA@"
	db "TERU-SAMA@"
	db "BAIE MEPO@"
	db "ECAILLEDRACO@"
	db "ADN. BERZERK@"
	db "TERU-SAMA@"
	db "DEF.SPE. +@"
	db "TERU-SAMA@"
	db "CENDRESACREE@"
	db "MASSE BALL@"
	db "LETTRE FLEUR@"
	db "NIVEAU BALL@"
	db "APPAT BALL@"
	db "SPEED BALL@"
	db "TERU-SAMA@"
	db "BALLE LUM.@"
	db "COPAIN BALL@"
	db "LUNE BALL@"
	db "LOVE BALL@"
	db "BOITE NORMAL@"
	db "JOLIE BOITE@"
	db "PIERRESOLEIL@"
	db "RUBAN A POIS@"
	db "TERU-SAMA@"
	db "EVOLUTOR@"
	db "BAIE ORAN@"
	db "BAIE SITRUS@"
	db "CARAPUCE'A'O@"
	db "TERU-SAMA@"
	db "PARC BALL@"
	db "ARCENCI'AILE@"
	db "TERU-SAMA@"
	db "MORC. BRIQUE@"
	db "LETTRE SURF@"
	db "LETRBLEUCIEL@"
	db "LETRPORTRAIT@"
	db "LETRCHARME@"
	db "LETTRE EVOLI@"
	db "LETTRE MORPH@"
	db "LETRCIELBLEU@"
	db "LETRMUSIQUE@"
	db "LETTREMIRAGE@"
	db "TERU-SAMA@"
	db "CT01@"
	db "CT02@"
	db "CT03@"
	db "CT04@"
	db "TERU-SAMA@"
	db "CT05@"
	db "CT06@"
	db "CT07@"
	db "CT08@"
	db "CT09@"
	db "CT10@"
	db "CT11@"
	db "CT12@"
	db "CT13@"
	db "CT14@"
	db "CT15@"
	db "CT16@"
	db "CT17@"
	db "CT18@"
	db "CT19@"
	db "CT20@"
	db "CT21@"
	db "CT22@"
	db "CT23@"
	db "CT24@"
	db "CT25@"
	db "CT26@"
	db "CT27@"
	db "CT28@"
	db "TERU-SAMA@"
	db "CT29@"
	db "CT30@"
	db "CT31@"
	db "CT32@"
	db "CT33@"
	db "CT34@"
	db "CT35@"
	db "CT36@"
	db "CT37@"
	db "CT38@"
	db "CT39@"
	db "CT40@"
	db "CT41@"
	db "CT42@"
	db "CT43@"
	db "CT44@"
	db "CT45@"
	db "CT46@"
	db "CT47@"
	db "CT48@"
	db "CT49@"
	db "CT50@"
	db "CS01@"
	db "CS02@"
	db "CS03@"
	db "CS04@"
	db "CS05@"
	db "CS06@"
	db "CS07@"
	db "TERU-SAMA@"
	db "TERU-SAMA@"
	db "TERU-SAMA@"
	db "TERU-SAMA@"
	db "TERU-SAMA@"
	db "TERU-SAMA@"
	db "?@"
