 	db "ECRAS'FACE@"
 	db "POING KARATE@"
 	db "TORGNOLES@"
 	db "DETRICANON@"
 	db "PSYKOUD'BOUL@"
 	db "JACKPOT@"
 	db "POING DE FEU@"
 	db "POINGLACE@"
 	db "POING ECLAIR@"
 	db "GRIFFE@"
 	db "VENT FEERIK@"
 	db "EXPLOFORCE@"
 	db "MUR DE FER@"
 	db "DANSE-LAMES@"
 	db "COUPE@"
 	db "TORNADE@"
 	db "CRU-AILE@"
 	db "CYCLONE@"
 	db "VOL@"
 	db "BOURDON@"
 	db "SOUPLESSE@"
 	db "FOUET LIANES@"
 	db "ECRASEMENT@"
 	db "DOUBLE PIED@"
 	db "ULTIMAWASHI@"
 	db "BOUTEFEU@"
 	db "MAWASHI GERI@"
 	db "JET DE SABLE@"
 	db "COUP D'BOULE@"
 	db "KOUD'KORNE@"
 	db "FURIE@"
 	db "EMPAL'KORNE@"
 	db "CHARGE@"
 	db "PLAQUAGE@"
 	db "LIGOTAGE@"
 	db "BELIER@"
 	db "MANIA@"
 	db "DAMOCLES@"
 	db "MIMI-QUEUE@"
 	db "DARD-VENIN@"
 	db "DOUBLE DARD@"
 	db "DARD-NUEE@"
 	db "GROZ'YEUX@"
 	db "MORSURE@"
 	db "RUGISSEMENT@"
 	db "HURLEMENT@"
 	db "BERCEUSE@"
 	db "ULTRASON@"
 	db "SONICBOOM@"
 	db "ENTRAVE@"
 	db "ACIDE@"
 	db "FLAMMECHE@"
 	db "LANCE-FLAMME@"
 	db "BRUME@"
 	db "PISTOLET A O@"
 	db "HYDROCANON@"
 	db "SURF@"
 	db "LASER GLACE@"
 	db "BLIZZARD@"
 	db "RAFALE PSY@"
 	db "BULLES D'O@"
 	db "ONDE BOREALE@"
 	db "ULTRALASER@"
 	db "PICPIC@"
 	db "BEC VRILLE@"
 	db "SACRIFICE@"
 	db "CANICULE@"
 	db "RIPOSTE@"
 	db "FRAPPE ATLAS@"
 	db "FORCE@"
 	db "VOLE-VIE@"
 	db "MEGA-SANGSUE@"
 	db "VAMPIGRAINE@"
 	db "CROISSANCE@"
 	db "TRANCH'HERBE@"
 	db "LANCE-SOLEIL@"
 	db "POUDRE TOXIC@"
 	db "PARA-SPORE@"
 	db "PODURE DODO@"
 	db "DANSE-FLEUR@"
 	db "SECRETION@"
 	db "DRACO-RAGE@"
 	db "DANSEFLAMME@"
 	db "ECLAIR@"
 	db "TONNERRE@"
 	db "CAGE-ECLAIR@"
 	db "FATAL-FOUDRE@"
 	db "JET-PIERRES@"
 	db "SEISME@"
 	db "ABIME@"
 	db "TUNNEL@"
 	db "TOXIK@"
 	db "CHOC MENTAL@"
 	db "PSYKO@"
 	db "HYPNOSE@"
 	db "YOGA@"
 	db "HATE@"
 	db "VIVE-ATTAQUE@"
 	db "FRENESIE@"
 	db "TELEPORT@"
 	db "TENEBRES@"
 	db "COPIE@"
 	db "GRINCEMENT@"
 	db "REFLET@"
 	db "SOIN@"
 	db "ARMURE@"
 	db "LILIPUT@"
 	db "BROUILLARD@"
 	db "ONDE FOLIE@"
 	db "REPLI@"
 	db "BOUL'ARMURE@"
 	db "BOUCLIER@"
 	db "MUR LUMIERE@"
 	db "BUEE NOIRE@"
 	db "PROTECTION@"
 	db "PUISSANCE@"
 	db "PATIENCE@"
 	db "METRONOME@"
 	db "MIMIQUE@"
 	db "DESTRUCTION@"
 	db "STRIDO-SON@"
 	db "LECHOUILLE@"
 	db "DRACO-CHOC@"
 	db "DETRITUS@"
 	db "MASSD'OS@"
 	db "DEFLAGRATION@"
 	db "CASCADE@"
 	db "CLAQUOIR@"
 	db "METEORES@"
 	db "AQUA-JET@"
 	db "PICANON@"
 	db "LUMINOCANON@"
 	db "AMNESIE@"
 	db "FEU FOLLET@"
 	db "E-COQUE@"
 	db "PIED VOLTIGE@"
 	db "INTIMIDATION@"
 	db "DEVOREVE@"
 	db "POLIROCHE@"
 	db "CANON GRAINE@"
 	db "VAMPIRISME@"
 	db "GROBISOUS@"
 	db "PIQUE@"
 	db "MORPHING@"
 	db "ECUME@"
 	db "UPPERCUT@"
 	db "SPORE@"
 	db "FLASH@"
 	db "VAGUE PSY@"
 	db "TREMPETTE@"
 	db "ACIDARMURE@"
 	db "PINCE-MASSE@"
 	db "EXPLOSION@"
 	db "DIRECT TOXIC@"
 	db "OSMERANG@"
 	db "REPOS@"
 	db "EBOULEMENT@"
 	db "CROC DE MORT@"
 	db "AFFUTAGE@"
 	db "CONVERSION@"
 	db "TRIPLATTAQUE@"
 	db "CROC FATAL@"
 	db "TRANCHE@"
 	db "CLONAGE@"
 	db "LUTTE@"
 	db "GRIBOUILLAGE@"
 	db "ECLAIR FOU@"
 	db "LARCIN@"
 	db "PLAIE-CROIX@"
 	db "LIRE-ESPRIT@"
 	db "CAUCHEMAR@"
 	db "ROUE DE FEU@"
 	db "TETE DE FER@"
 	db "MALEDICTION@"
 	db "FLEAU@"
 	db "CONVERSION2@"
 	db "AEROBLAST@"
 	db "SPORE COTON@"
 	db "CONTRE@"
 	db "DEPIT@"
 	db "POUDREUSE@"
 	db "ABRI@"
 	db "MACH PUNCH@"
 	db "GRIMACE@"
 	db "FEINTE@"
 	db "DOUX BAISER@"
 	db "COGNOBIDON@"
 	db "BOMB-BEURK@"
 	db "COUD'BOUE@"
 	db "OCTAZOOKA@"
 	db "PICOTS@"
 	db "ELECANON@"
 	db "CLAIRVOYANCE@"
 	db "PRLVT DESTIN@"
 	db "REQUIEM@"
 	db "VENT GLACE@"
 	db "LAME D'AIR@"
 	db "VIBROBSCUR@"
 	db "TELLURIFORCE@"
 	db "COLERE@"
 	db "TEMPTESABLE@"
 	db "GIGA-SANGSUE@"
 	db "TENACITE@"
 	db "CHARME@"
 	db "ROULADE@"
 	db "FAUX-CHAGE@"
 	db "VANTARDISE@"
 	db "LAIT A BOIRE@"
 	db "ETINCELLE@"
 	db "TAILLADE@"
 	db "AILE D'ACIER@"
 	db "REGARD NOIR@"
 	db "ATTRACTION@"
 	db "BLABLA DODO@"
 	db "GLAS DE SOIN@"
 	db "RETOUR@"
 	db "CADEAU@"
 	db "ECLAT MAGIK@"
 	db "RUNE PROTECT@"
 	db "BALANCE@"
 	db "FEU SACRE@"
 	db "AMPLEUR@"
 	db "DYNAMOPOING@"
 	db "MEGACORNE@"
 	db "DRACOSOUFFLE@"
 	db "RELAIS@"
 	db "ENCORE@"
 	db "POURSUITE@"
 	db "TOUR RAPIDE@"
 	db "MACHINATION@"
 	db "QUEUE DE FER@"
 	db "GRIFFE ACIER@"
 	db "CORPS PERDU@"
 	db "AURORE@"
 	db "SYNTHESE@"
 	db "RAYON LUNE@"
 	db "PUISS.CACHE@"
 	db "COUP CROIX@"
 	db "OURAGAN@"
 	db "DANSE PLUIE@"
 	db "ZENITH@"
 	db "MACHOUILLE@"
 	db "VOILE MIROIR@"
 	db "GRIFFE OMBRE@"
 	db "VIT.EXTREME@"
 	db "POUV.ANTIQUE@"
 	db "BALL'OMBRE@"
 	db "PRESCIENCE@"
 	db "ECLATE-ROC@"
 	db "SIPHON@"
 	db "TUNNELIER@"
 	db "POUV.LUNAIRE@"
 	db "CALINERIE@"
 	db "GLACIATION@"